FROM ubuntu:24.04

ARG DNS=localhost
ARG HTTP_APP_PORT=8080

RUN apt-get update -y

####################################
## INSTALAMOS PAQUETES NECESARIOS
####################################
RUN apt-get install -y openjdk-11-jdk curl nginx
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
RUN apt-get install -y nodejs
RUN apt-get install -y npm 

# Instalamos Angular CLI
RUN npm install -g @angular/cli@21.0.5

#################################
## CREAMOS DIRECTORIOS
#################################
RUN mkdir -p /srv/aplicaciones/backend

####################################
## COPIAMOS ENVIRONMENT y JARS
####################################
COPY environments/backend.env /srv/aplicaciones/backend/.env
COPY java/devsuTest* /srv/aplicaciones/backend/Backend.jar

# Exponer puertos
EXPOSE 80 8080

#################################
### Script de inicio
#################################
##CMD java -jar /srv/aplicaciones/backend/Backend.jar 
WORKDIR /srv/aplicaciones/backend
CMD ["java","-jar","Backend.jar"]

##############################################
### INSTALAMOS ANGULAR
##############################################
COPY frontend/ /srv/aplicaciones/frontend
COPY environments/frontend.ts /srv/aplicaciones/frontend/src/environments/environment.ts

WORKDIR /srv/aplicaciones/frontend
RUN npm install && ng build --configuration production

#################################
### CONFIGURAMOS NGINX
#################################
COPY nginx/* /etc/nginx/sites-available/
RUN ln -s /etc/nginx/sites-available/devsu.demo /etc/nginx/sites-enabled/ \
    && rm -f /etc/nginx/sites-enabled/default

CMD nginx -g 'daemon off';

#RUN sed -i "s/<DNS>/$DNS/g" /etc/nginx/sites-available/devsu.demo